project:
  type: website

website:
  title: "backseat_programmer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DimitarVanguelov
format:
  html:
    theme: simplex
    css: styles.css



